apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0   # no downtime
      maxSurge: 1         # add one extra pod during update
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
        - name: web
          image: messaging-app:2.0       # <<— updated image tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "blue-2.0"
          command: ["/bin/bash", "-lc"]
          args:
            - |
              python manage.py migrate && \
              python manage.py runserver 0.0.0.0:8000
          readinessProbe:
            httpGet: { path: "/", port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 15
