apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>
  database: <base64-encoded-database-name>
  root-password: <base64-encoded-root-password>