name: CI (messaging_app)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r messaging_app/requirements.txt
      - name: Lint
        run: flake8 messaging_app --config .flake8
      - name: Tests
        run: pytest -q messaging_app/tests
