pipeline {
  agent any
  options { timestamps() }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
        dir('messaging_app') { sh 'ls -la' }
      }
    }
    stage('Install') {
      steps {
        dir('messaging_app') {
          sh '''
            python3 -m venv .venv
            . .venv/bin/activate
            pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install pytest pytest-cov flake8 coverage
          '''
        }
      }
    }
    stage('Lint') {
      steps {
        dir('messaging_app') {
          sh '. .venv/bin/activate && flake8 .'
        }
      }
    }
    stage('Test') {
      steps {
        dir('messaging_app') {
          sh '''
            . .venv/bin/activate
            mkdir -p reports
            pytest -q --junitxml=reports/junit.xml --cov=. --cov-report=xml:reports/coverage.xml
          '''
        }
        junit 'messaging_app/reports/junit.xml'
      }
    }
  }
}
