name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        working-directory: messaging_app
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov flake8 coverage
      - name: Lint
        working-directory: messaging_app
        run: flake8 .
      - name: Test
        working-directory: messaging_app
        run: |
          mkdir -p reports
          pytest -q --junitxml=reports/junit.xml --cov=. --cov-report=xml:reports/coverage.xml
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: messaging_app/reports
